MVC/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Domain.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Services.Interfaces;
using Services.Services;
using Services.ViewModels;

namespace MVC.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;


        public CompanyController(ICompanyService companyService)
        {
            _companyService = companyService;
        }

        public IActionResult Index()
        {
            //ViewBag.Title = "Company";
            ViewBag.Title = "Perfil de Empresa";

            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;


            var indexViewModel = new CompanyIndexViewModel()
            {
                CompanyList = _companyService.GetAll().ToList(),
                CurrentUserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value),
                IsAdmin = isAdmin
            };
            return View(indexViewModel);
        }

        public IActionResult Create()
        {
            //ViewBag.Title = "Company - Create";
            ViewBag.Title = "Perfil de Empresa / Criar";
            return View(new CompanyViewModel());
        }

        public IActionResult CreateModal()
        {
            //ViewBag.Title = "Company - Create";
            ViewBag.Title = "Perfil de Empresa / Criar";
            return PartialView(nameof(Create), new CompanyViewModel() { FromModal = true });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CompanyViewModel companyViewModel)
        {

            if (ModelState.IsValid)
            {
                companyViewModel.UserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value);

                _companyService.Add(companyViewModel);

                if (companyViewModel.FromModal)
                {
                    var scenarioGeneralViewModel = new ScenarioGeneralViewModel();
                    scenarioGeneralViewModel.CompanyList = _companyService.GetAll();
                    return PartialView("DropdownCompany", scenarioGeneralViewModel);
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            if (companyViewModel.FromModal)
            {
                Response.StatusCode = 400;
                return PartialView(nameof(Create), companyViewModel);
            }
            else
            {
                return View(companyViewModel);
            }
        }

        public IActionResult Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var companyViewModel = _companyService.Get(id);
            if (companyViewModel == null)
            {
                return NotFound();
            }
            return PartialView(companyViewModel);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Title = "Perfil de Empresa / Editar";

            if (id == 0)
            {
                return NotFound();
            }

            var viewModel = _companyService.Get(id);
            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var canEdit = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value).Equals(viewModel.UserId.Value);

            if (!isAdmin && !canEdit)
            {
                return Unauthorized();
            }

            var companyViewModel = _companyService.Get(id);
            if (companyViewModel == null)
            {
                return NotFound();
            }
            return View(companyViewModel);
        }

        [HttpPost]
        public IActionResult Edit(int id, CompanyViewModel companyViewModel)
        {
            if (id != companyViewModel.Id)
            {
                return NotFound();
            }

            var viewModel = _companyService.Get(id);
            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var canEdit = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value).Equals(viewModel.UserId.Value);

            if (!isAdmin && !canEdit)
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _companyService.Update(companyViewModel);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_companyService.GetAll().Any(e => e.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(companyViewModel);
        }

        [HttpGet]
        public IActionResult TableList()
        {
            return PartialView(_companyService.GetAll());
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {

            var viewModel = _companyService.Get(id);
            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var canEdit = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value).Equals(viewModel.UserId.Value);

            if (!isAdmin && !canEdit)
            {
                return Unauthorized();
            }

            if (_companyService.CanRemove(id))
            {
                _companyService.Remove(id);
            }
            else
            {
                //return StatusCode(500, "This item is being used by some Scenario and can not be removed");
                return StatusCode(500, "Este item está sendo usado por algum Cenário e não pode ser removido");
            }



            var indexViewModel = new CompanyIndexViewModel()
            {
                CompanyList = _companyService.GetAll().ToList(),
                CurrentUserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value),
                IsAdmin = isAdmin
            };

            return PartialView(nameof(TableList), indexViewModel);
        }
    }
}

MVC/Controllers/ScenarioController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Domain.Entities;
using System.Collections.Generic;
using Services.ViewModels;
using Services.Interfaces;
using System.Security.Claims;
using System;
using Domain.Enums;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using System.IO;
using MimeKit;

namespace MVC.Controllers
{
    public class AuthorizeRolesAttribute : AuthorizeAttribute
    {
        public AuthorizeRolesAttribute(params Roles[] allowedRoles)
        {
            var allowedRolesAsStrings = allowedRoles.Select(x => (int)x);
            Roles = string.Join(",", allowedRolesAsStrings);
        }
    }

    public class ScenarioController : Controller
    {
        private readonly IScenarioService _scenarioService;
        private readonly IConflictTypeService _conflictTypeService;
        private readonly ISeverityService _severityService;
        private readonly ISEPhaseService _sePhaseService;
        private readonly IManageConflictService _manageConflictService;
        private readonly IEffectConsequenceService _effectConsequenceService;
        private readonly ICompanyService _companyService;
        private readonly IInterviewService _interviewService;
        public ScenarioController(IScenarioService scenarioService, IConflictTypeService conflictTypeService,
            ISeverityService severityService, ISEPhaseService sePhaseService, IManageConflictService manageConflictService,
            IEffectConsequenceService effectConsequenceService, ICompanyService companyService, IInterviewService interviewService)
        {
            _scenarioService = scenarioService;
            _conflictTypeService = conflictTypeService;
            _severityService = severityService;
            _sePhaseService = sePhaseService;
            _manageConflictService = manageConflictService;
            _effectConsequenceService = effectConsequenceService;
            _companyService = companyService;
            _interviewService = interviewService;
        }

        public IActionResult Index()
        {
            //ViewBag.Title = "Scenarios";
            ViewBag.Title = "Cenário";

            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var indexViewModel = new ScenarioIndexViewModel()
            {
                ScenarioViewModelList = _scenarioService.GetAll(),
                IsAdmin = isAdmin,
                CurrentUserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value),
                ConflictTypeList = _conflictTypeService.GetAll(),
                ManageConflictList = _manageConflictService.GetAll(),
                SEPhaseList = _sePhaseService.GetAll(),
                SeverityList = _severityService.GetAll()
            };
            return View(indexViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Title = "Cenário / Criar";

            var scenarioViewModel = new ScenarioViewModel();

            scenarioViewModel.ScenarioConflictViewModel.ConflictTypeList = _conflictTypeService.GetAll();
            scenarioViewModel.ScenarioConflictViewModel.SeverityList = _severityService.GetAll();
            scenarioViewModel.ScenarioConflictViewModel.SEPhaseList = _sePhaseService.GetAll();
            scenarioViewModel.ScenarioConflictViewModel.ManageConflictList = _manageConflictService.GetAll();
            scenarioViewModel.ScenarioConflictJourneyViewModel.EffectConsequenceList = _effectConsequenceService.GetAll();
            scenarioViewModel.ScenarioGeneralViewModel.CompanyList = _companyService.GetAll();
            scenarioViewModel.ScenarioGeneralViewModel.InterviewList = _interviewService.GetAll();

            return View(scenarioViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ScenarioViewModel scenarioViewModel)
        {

            if (scenarioViewModel.ScenarioGeneralViewModel.CompanyId == 0)
            {
                scenarioViewModel.ScenarioGeneralViewModel.CompanyId = null;
            }

            if (scenarioViewModel.ScenarioGeneralViewModel.ScenarioOrigin.Equals(ScenarioOrigin.Interview) && scenarioViewModel.ScenarioGeneralViewModel.InterviewId == 0)
            {
                //ModelState.AddModelError(nameof(scenarioViewModel.ScenarioGeneralViewModel.InterviewId), "The Interview field is required.");
                ModelState.AddModelError(nameof(scenarioViewModel.ScenarioGeneralViewModel.InterviewId), "A Entrevista é obrigatória.");
            }

            if (ModelState.IsValid)
            {
                scenarioViewModel.ScenarioGeneralViewModel.UserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value);
                _scenarioService.Add(scenarioViewModel);


                return RedirectToAction(nameof(Index));
            }

            scenarioViewModel.ScenarioConflictViewModel.ConflictTypeList = _conflictTypeService.GetAll();
            scenarioViewModel.ScenarioConflictViewModel.SeverityList = _severityService.GetAll();
            scenarioViewModel.ScenarioConflictViewModel.SEPhaseList = _sePhaseService.GetAll();
            scenarioViewModel.ScenarioConflictViewModel.ManageConflictList = _manageConflictService.GetAll();
            scenarioViewModel.ScenarioConflictJourneyViewModel.EffectConsequenceList = _effectConsequenceService.GetAll();
            scenarioViewModel.ScenarioGeneralViewModel.CompanyList = _companyService.GetAll();
            scenarioViewModel.ScenarioGeneralViewModel.InterviewList = _interviewService.GetAll();

            return View(scenarioViewModel);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateGeneral(ScenarioGeneralViewModel viewModel)
        {
            if (viewModel.TranscriptionFile != null)
            {

                var extension = Path.GetExtension(viewModel.TranscriptionFile.FileName);
                if (Path.GetExtension(viewModel.TranscriptionFile.FileName) != ".txt" && Path.GetExtension(viewModel.TranscriptionFile.FileName) != ".doc" && Path.GetExtension(viewModel.TranscriptionFile.FileName) != ".docx")
                {
                    ModelState.AddModelError(nameof(viewModel.TranscriptionFile), "Tipo de arquivo inválido.");

                }
            }

            if (viewModel.AudioFile != null)
            {

                var extension = Path.GetExtension(viewModel.AudioFile.FileName);
                if (Path.GetExtension(viewModel.AudioFile.FileName) != ".mp3" && Path.GetExtension(viewModel.AudioFile.FileName) != ".wma" && Path.GetExtension(viewModel.AudioFile.FileName) != ".aac")
                {
                    ModelState.AddModelError(nameof(viewModel.AudioFile), "Tipo de arquivo inválido.");

                }
            }

            if (viewModel.ScenarioOrigin.Equals(ScenarioOrigin.Interview) && viewModel.InterviewId == 0)
            {
                ModelState.Clear();
                viewModel.HasError = true;
                //ModelState.AddModelError(nameof(ViewModel.InterviewId), "The Interview field is required.");
                ModelState.AddModelError(nameof(viewModel.InterviewId), "A Entrevista é obrigatória.");
            }

            if (ModelState.IsValid)
            {
                viewModel.UserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value);

                viewModel = await _scenarioService.AddGeneral(viewModel);
                ModelState.Clear();

            }
            else
            {
                ModelState.Remove("HasError");
                viewModel.HasError = true;

            }

            viewModel.CompanyList = _companyService.GetAll();
            viewModel.InterviewList = _interviewService.GetAll();

            return PartialView("_FormControlGeneral", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateStakeholders(ScenarioStakeholdersViewModel ViewModel)
        {

            if (ModelState.IsValid)
            {

                ViewModel = _scenarioService.AddStakeholders(ViewModel);

                var index = ViewModel.Stakeholders.FindIndex(x => x.Id == ViewModel.StakeholderRelatorId);

                if (index >= 0)
                {
                    ViewModel.RelatorIndex.Add(index);
                }

                ModelState.Clear();

            }
            else
            {
                ModelState.Remove("HasErrorStakeholders");
                ViewModel.HasErrorStakeholders = true;

            }

            return PartialView("_FormControlStakeholders", ViewModel);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateConflict(ScenarioConflictViewModel ViewModel)
        {

            if (ModelState.IsValid)
            {

                ViewModel = _scenarioService.AddConflict(ViewModel);

                ModelState.Clear();

            }
            else
            {
                ModelState.Remove("HasErrorConflict");
                ViewModel.HasErrorConflict = true;

            }


            ViewModel.ConflictTypeList = _conflictTypeService.GetAll();
            ViewModel.SeverityList = _severityService.GetAll();
            ViewModel.SEPhaseList = _sePhaseService.GetAll();
            ViewModel.ManageConflictList = _manageConflictService.GetAll();

            return PartialView("_FormControlConflict", ViewModel);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateConflictJourney(ScenarioConflictJourneyViewModel ViewModel)
        {

            if (ModelState.IsValid)
            {

                ViewModel = _scenarioService.AddConflictJourney(ViewModel);

                ModelState.Clear();

            }

MVC/Views/Scenario/Edit.cshtml
@model Services.ViewModels.ScenarioViewModel;
@using Domain.Enums;

<form asp-controller="Scenario" asp-action="Edit" method="post" class="form-horizontal" role="form" autocomplete="off">
    <partial name="FormControl" model="Model">
        @*<button class="btn btn-primary">Save</button>
        <a asp-controller="Scenario" asp-action="Index" id="cancel" class="btn btn-secondary">Cancel</a>*@
        <button class="btn btn-primary">Salvar</button>
        <a asp-controller="Scenario" asp-action="Index" id="cancel" class="btn btn-secondary">Cancelar</a>
</form>

<partial name="GenericModal">


    @section Scripts{

        <script type="text/javascript">

            $('#ConflictTypeIds').select2({
                placeholder: "Procurar..."
            });

            $('#SEPhaseIds').select2({
                    placeholder: "Procurar..."
            });

            $('#SeverityId').select2({
                placeholder: "Procurar..."
            });

            $('#ManageConflictIds').select2({
                placeholder: "Procurar..."
            });

            $('#EffectConsequenceIds').select2({
                placeholder: "Procurar..."
            });

            $('#CompanyId').select2({
                placeholder: "Procurar..."
            });

            $('#SeverityId').select2({
                placeholder: "Procurar..."
            });

            $(document).ready(function () {

                $(document).on('click', '#create-conflict-type', function () {
                    $.ajax({
                        cache: false,
                        type: 'GET',
                        url: '@Url.Action("CreateModal","ConflictType")',
                        success: function (data) {

                            $('#generic-modal-replace-body').html(data);

                            $('#generic-modal-replace-body').data('id-replace', 'replace-dd-conflict-type');

                            $('#generic-modal').modal('show');
                        }
                    });
                });

                $(document).on('click', '#create-se-phase', function () {
                    $.ajax({
                        cache: false,
                        type: 'GET',
                        url: '@Url.Action("CreateModal","SEPhase")',
                        success: function (data) {

                            $('#generic-modal-replace-body').html(data);

                            $('#generic-modal-replace-body').data('id-replace', 'replace-dd-se-phase');

                            $('#generic-modal').modal('show');
                        }
                    });
                });

                $(document).on('click', '#create-severity', function () {
                    $.ajax({
                        cache: false,
                        type: 'GET',
                        url: '@Url.Action("CreateModal","Severity")',
                        success: function (data) {

                            $('#generic-modal-replace-body').html(data);

                            $('#generic-modal-replace-body').data('id-replace', 'replace-dd-se-phase');

                            $('#generic-modal').modal('show');
                        }
                    });
                });

                $(document).on('click', '#create-company', function () {
                    $.ajax({
                        cache: false,
                        type: 'GET',
                        url: '@Url.Action("CreateModal","Company")',
                        success: function (data) {

                            $('#generic-modal-replace-body').html(data);

                            $('#generic-modal-replace-body').data('id-replace', 'replace-dd-company');

                            $('#generic-modal').modal('show');
                        }
                    });
                });

                $(document).on('click', '#create-manage-conflict', function () {
                    $.ajax({
                        cache: false,
                        type: 'GET',
                        url: '@Url.Action("CreateModal","ManageConflict")',
                        success: function (data) {

                            $('#generic-modal-replace-body').html(data);

                            $('#generic-modal-replace-body').data('id-replace', 'replace-dd-manage-conflict');

                            $('#generic-modal').modal('show');
                        }
                    });
                });

                $(document).on('click', '#create-effect-consequence', function () {
                    $.ajax({
                        cache: false,
                        type: 'GET',
                        url: '@Url.Action("CreateModal","EffectConsequence")',
                        success: function (data) {

                            $('#generic-modal-replace-body').html(data);

                            $('#generic-modal-replace-body').data('id-replace', 'replace-dd-effect-consequence');

                            $('#generic-modal').modal('show');
                        }
                    });
                });

                $(document).on('click', '#create-company', function () {
                    $.ajax({
                        cache: false,
                        type: 'GET',
                        url: '@Url.Action("CreateModal","Company")',
                        success: function (data) {

                            $('#generic-modal-replace-body').html(data);

                            $('#generic-modal-replace-body').data('id-replace', 'replace-dd-company');

                            $('#generic-modal').modal('show');
                        }
                    });
                });

                $(document).on('click', '#create-interview', function () {
                    $.ajax({
                        cache: false,
                        type: 'GET',
                        url: '@Url.Action("CreateModal","Interview")',
                        success: function (data) {

                            $('#generic-modal-replace-body').html(data);

                            $('#generic-modal-replace-body').data('id-replace', 'replace-dd-se-phase');

                            $('#generic-modal').modal('show');
                        }
                    });
                });

                $(document).on('click', '#save', function (event) {
                    event.preventDefault();
                    var $form = $('#generic-modal-replace-body').find('form');

                    $.ajax({
                        type: 'POST',
                        url: $form.prop('action'),
                        data: $form.serialize()
                    }).done(function (data) {
                            var idReplace = $('#generic-modal-replace-body').data('id-replace');

                            $('#' + idReplace).html(data);
                            $('#' + idReplace).find('.dropdown-select2').select2({
                                placeholder: "Search..."
                            });
                            $('#generic-modal').modal('hide');
                    }).fail(function (data) {
                        $('#generic-modal-replace-body').html(data.responseText);


                        });
                });

                if ($('#ScenarioOrigin').val() != @((int)ScenarioOrigin.Interview)) {
                    $('#replace-dd-interview').hide();
                }

                $(document).on('change', '#ScenarioOrigin', function () {
                    if ($('#ScenarioOrigin').val() != @((int)ScenarioOrigin.Interview)) {
                        $('#replace-dd-interview').hide();
                    } else {
                        $('#replace-dd-interview').show();

                    }
                });

                $(document).on('change', '.relator-index', function () {
                    $(".relator-index").prop('checked',false);
                    $(this).prop('checked',true);
                });


            });
        </script>

    }

MVC/Views/Scenario/FormControl.cshtml
@model Services.ViewModels.ScenarioViewModel;














@*<script type="text/javascript">
    $(document).ready(function () {
                        if ($('#ScenarioOrigin').val() != @((int)ScenarioOrigin.Interview)) {
                        $('#replace-dd-interview').hide();
                    }

                    $(document).on('change', '#ScenarioOrigin', function () {
                        if ($('#ScenarioOrigin').val() != @((int)ScenarioOrigin.Interview)) {
                            $('#replace-dd-interview').hide();
                        } else {
                            $('#replace-dd-interview').show();

                        }
                    });
                });

    </script>*@

MVC/Views/Scenario/TableList.cshtml
@using Services.Helpers;
@model ScenarioIndexViewModel;

<div class="d-flex justify-content-center">

    <div class="table-responsive col-md-12">
        <table class="table table-striped table-bordered" cellspacing="0" cellpadding="0" style="font-size: smaller;">
            <thead>
                <tr>
                    @*<th>Summary</th>
                        <th>Problem Description</th>
                        <th>Problem Summary</th>*@
                    @*<th>Resumo do Cenário</th>*@
                    <th>Problema</th>
                    <th>Tipo do Conflito</th>
                    <th>Administração de Conflito</th>
                    <th>Fase ES</th>
                    <th>Status</th>


                    <th class="actions" style="width: 145px">Ações</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.ScenarioViewModelList != null)
                {

                    @foreach (var item in Model.ScenarioViewModelList)
                    {
                        string conflicts = "";
                        string manageConflict = "";
                        string SEPhase = "";
                        @for (int i = 0; i < item.ScenarioConflictViewModel.ConflictTypeIds.Count(); i++)
                        {
                            var conflictId = item.ScenarioConflictViewModel.ConflictTypeIds.ElementAt(i);
                            conflicts += Model.ConflictTypeList.FirstOrDefault(y => y.Id == conflictId)?.Type;
                            if (i < item.ScenarioConflictViewModel.ConflictTypeIds.Count() - 1)
                            {
                                conflicts += " | ";

                            }
                        }
                        @for (int i = 0; i < item.ScenarioConflictViewModel.ManageConflictIds.Count(); i++)
                        {
                            var manageConflictId = item.ScenarioConflictViewModel.ManageConflictIds.ElementAt(i);
                            manageConflict += Model.ManageConflictList.FirstOrDefault(y => y.Id == manageConflictId)?.Style;
                            if (i < item.ScenarioConflictViewModel.ManageConflictIds.Count() - 1)
                            {
                                manageConflict += " | ";

                            }
                        }
                        @for (int i = 0; i < item.ScenarioConflictViewModel.SEPhaseIds.Count(); i++)
                        {
                            var SEPhaseId = item.ScenarioConflictViewModel.SEPhaseIds.ElementAt(i);
                            SEPhase += Model.SEPhaseList.FirstOrDefault(y => y.Id == SEPhaseId)?.Phase;
                            if (i < item.ScenarioConflictViewModel.SEPhaseIds.Count() - 1)
                            {
                                SEPhase += " | ";

                            }
                        }
                <tr id="@item.Id">

                    @*<td>@item.ScenarioGeneralViewModel.Summary.Substring(0, item.ScenarioGeneralViewModel.Summary.Length >= 30 ? 30 : item.ScenarioGeneralViewModel.Summary.Length)</td>*@
                    <td>@(item.ScenarioGeneralViewModel.ProblemSummary.Substring(0, item.ScenarioGeneralViewModel.ProblemSummary.Length >= 100 ? 100 : item.ScenarioGeneralViewModel.ProblemSummary.Length) + (item.ScenarioGeneralViewModel.ProblemSummary.Length >= 100 ? " ..." : ""))</td>
                    <td>
                        @conflicts@*.Substring(0, item.ScenarioGeneralViewModel.ProblemSummary.Length >= 30 ? 30 : item.ScenarioGeneralViewModel.ProblemSummary.Length)*@
                    </td>
                    <td>
                        @manageConflict
                    </td>
                    <td>@SEPhase</td>
                    <td>@(item.ScenarioGeneralViewModel.Status.HasValue? item.ScenarioGeneralViewModel.Status.Value.GetDescription() : "")</td>
                    <td class="actions">
                        <a href="#" id="details-button" class="btn"><i class="fa fa-search"></i></a>
                        @if (Model.IsAdmin || Model.CurrentUserId == item.ScenarioGeneralViewModel.UserId)
                        {
                            <a asp-controller="Scenario" asp-action="Edit" asp-route-id="@item.Id" class="btn"><i class="fa fa-edit"></i></a>
                            <a href="#" id="remove-button" class="btn" data-toggle="modal" data-target="#delete-modal"><i class="fa fa-trash"></i></a>
                        }
                    </td>

                </tr>
                    }
                }
            </tbody>
        </table>
    </div>

</div>

@*<nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Anterior</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Próxima</a>
            </li>
        </ul>
    </nav>*@

MVC/Views/Scenario/_FormControlStakeholders.cshtml
@model Services.ViewModels.ScenarioStakeholdersViewModel;

<input asp-for="HasErrorStakeholders" type="hidden" />

<div id="replace-stakeholder">
    <partial name="_Stakeholders" model="Model">
</div>