MVC/Controllers/SEPhaseController.cs
using System;
using System.Linq;
using System.Security.Claims;
using Domain.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Services.Interfaces;
using Services.ViewModels;

namespace MVC.Controllers
{
    public class SEPhaseController : Controller
    {
        private readonly ISEPhaseService _sePhaseService;


        public SEPhaseController(ISEPhaseService sePhaseService)
        {
            _sePhaseService = sePhaseService;
        }

        public IActionResult Index()
        {
            //ViewBag.Title = "Software Engineer Phase";
            ViewBag.Title = "Fase da Engenharia de Software";

            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;


            var indexViewModel = new SEPhaseIndexViewModel()
            {
                SEPhaseList = _sePhaseService.GetAll().ToList(),
                CurrentUserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value),
                IsAdmin = isAdmin
            };
            return View(indexViewModel);

        }

        public IActionResult Create()
        {
            //ViewBag.Title = "Software Engineer Phase - Create";
            ViewBag.Title = "Fase da Engenharia de Software / Criar";
            return View(new SEPhaseViewModel());
        }

        public IActionResult CreateModal()
        {
            //ViewBag.Title = "Software Engineer Phase - Create";
            ViewBag.Title = "Fase da Engenharia de Software / Criar";
            return PartialView(nameof(Create), new SEPhaseViewModel() { FromModal = true });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SEPhaseViewModel sePhaseViewModel)
        {
            if (ModelState.IsValid)
            {
                sePhaseViewModel.UserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value);

                _sePhaseService.Add(sePhaseViewModel);

                if (sePhaseViewModel.FromModal)
                {
                    var scenarioConflictViewModel = new ScenarioConflictViewModel();
                    scenarioConflictViewModel.SEPhaseList = _sePhaseService.GetAll();
                    return PartialView("DropdownSEPhase", scenarioConflictViewModel);
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            if (sePhaseViewModel.FromModal)
            {
                Response.StatusCode = 400;
                return PartialView(nameof(Create), sePhaseViewModel);
            }
            else
            {
                return View(sePhaseViewModel);
            }
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var sePhaseViewModel = _sePhaseService.Get(id);
            if (sePhaseViewModel == null)
            {
                return NotFound();
            }
            return PartialView(sePhaseViewModel);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {

            ViewBag.Title = "Fase da Engenharia de Software / Editar";

            if (id == 0)
            {
                return NotFound();
            }

            var viewModel = _sePhaseService.Get(id);
            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var canEdit = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value).Equals(viewModel.UserId.Value);

            if (!isAdmin && !canEdit)
            {
                return Unauthorized();
            }

            var sePhaseViewModel = _sePhaseService.Get(id);
            if (sePhaseViewModel == null)
            {
                return NotFound();
            }
            return View(sePhaseViewModel);
        }

        [HttpPost]
        public IActionResult Edit(int id, SEPhaseViewModel sePhaseViewModel)
        {
            if (id != sePhaseViewModel.Id)
            {
                return NotFound();
            }

            var viewModel = _sePhaseService.Get(id);
            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var canEdit = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value).Equals(viewModel.UserId.Value);

            if (!isAdmin && !canEdit)
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _sePhaseService.Update(sePhaseViewModel);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_sePhaseService.GetAll().Any(e => e.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sePhaseViewModel);
        }

        [HttpGet]
        public IActionResult TableList()
        {
            return PartialView(_sePhaseService.GetAll());
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var viewModel = _sePhaseService.Get(id);
            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var canEdit = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value).Equals(viewModel.UserId.Value);

            if (!isAdmin && !canEdit)
            {
                return Unauthorized();
            }

            if (_sePhaseService.CanRemove(id))
            {
                _sePhaseService.Remove(id);
            }
            else
            {
                //return StatusCode(500, "This item is being used by some Scenario and can not be removed");
                return StatusCode(500, "Este item está sendo usado por algum Cenário e não pode ser removido");
            }



            var indexViewModel = new SEPhaseIndexViewModel()
            {
                SEPhaseList = _sePhaseService.GetAll().ToList(),
                CurrentUserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value),
                IsAdmin = isAdmin
            };

            return PartialView(nameof(TableList), indexViewModel);
        }
    }
}

MVC/Views/SEPhase/Create.cshtml
@model Services.ViewModels.SEPhaseViewModel;

<form asp-controller="SEPhase" asp-action="Create" method="post" class="form-horizontal" role="form" autocomplete="off">
    <partial name="FormControl" model="Model">
        @*<button id="save" class="btn btn-primary">Save</button>
        <a asp-controller="SEPhase" asp-action="Index" id="cancel" class="btn btn-secondary">Cancel</a>*@

        <button id="save" class="btn btn-primary">Salvar</button>
        @if (!Model.FromModal)
        {
            <a asp-controller="SEPhase" asp-action="Index" id="cancel" class="btn btn-secondary">Cancelar</a>
        }
</form>

MVC/Views/SEPhase/Details.cshtml
@model Services.ViewModels.SEPhaseViewModel;

<partial name="FormControl" model="Model">

MVC/Views/SEPhase/DropdownSEPhase.cshtml
@model Services.ViewModels.ScenarioConflictViewModel;

<label asp-for="@Model.SEPhaseIds" class="control-label"></label>
@*<i class="far fa-question-circle" data-toggle="tooltip" data-placement="top" title="Choose the software engineering phase in which the conflict occurred"></i>*@
<i class="far fa-question-circle" data-toggle="tooltip" data-placement="top" title="Escolha a Fase de Engenharia de Software em que o Conflito ocorreu"></i>

@*<select asp-for="@Model.SEPhaseIds" asp-items="@Model.SEPhaseSelectList" class="form-control dropdown-select2" multiple searchable="Search...">*@
<select asp-for="@Model.SEPhaseIds" asp-items="@Model.SEPhaseSelectList" class="form-control dropdown-select2" multiple searchable="Procurar...">
</select>

<span asp-validation-for="@Model.SEPhaseIds" class="text-danger"></span>

MVC/Views/SEPhase/Edit.cshtml
@model Services.ViewModels.SEPhaseViewModel;

    <form asp-controller="SEPhase" asp-action="Edit" method="post" class="form-horizontal" role="form" autocomplete="off">
        <input asp-for="UserId" type="hidden" />

        <partial name="FormControl" model="Model">
            @*<button id="save" class="btn btn-primary">Save</button>
            <a asp-controller="SEPhase" asp-action="Index" id="cancel" class="btn btn-secondary">Cancel</a>*@
            <button id="save" class="btn btn-primary">Salvar</button>
            <a asp-controller="SEPhase" asp-action="Index" id="cancel" class="btn btn-secondary">Cancelar</a>
    </form>

MVC/Views/SEPhase/FormControl.cshtml
@model Services.ViewModels.SEPhaseViewModel;

<input asp-for="Id" type="hidden" />
<input asp-for="FromModal" type="hidden" />

<div class="form-row">
    <div class="form-group col-6">
        <label asp-for="@Model.Phase" class="control-label"></label>
        @*<input asp-for="@Model.Phase" class="form-control" placeholder="Phase" />*@
        <input asp-for="@Model.Phase" class="form-control" placeholder="Fase da Engenharia de Software" />
        <span asp-validation-for="@Model.Phase" class="text-danger"></span>
    </div>
</div>

MVC/Views/SEPhase/Index.cshtml
@model SEPhaseIndexViewModel;

    <div class="d-flex justify-content-between bd-highlight mb-3">
        <div class="col-md-5">
            <h4>
                Lista Fases de Engenharia de Software
            </h4>
        </div>
        <div class="col-md-3">

        </div>
        <div class="p-1 col-md-4 bd-highlight">
            @*<a asp-controller="SEPhase" asp-action="Create" class="btn btn-primary pull-right h2">New Item</a>*@
            <a asp-controller="SEPhase" asp-action="Create" class="btn btn-primary pull-right h2">Nova Fase de Engenharia de Software</a>
        </div>


        <div class="p-1 col-md-6 bd-highlight">

            <div class="input-group h2">
                @*<input name="data[search]" class="form-control" id="search" type="text" placeholder="Search Items">*@
                @*<input name="data[search]" class="form-control" id="search" type="text" placeholder="Procurar Fase de Engenharia de Software">*@
                @*<button class="btn btn-primary" type="submit">
                    <span class="fa fa-search"></span>
                </button>*@
            </div>

        </div>

    </div>



<div id="list">
    <partial name="TableList" model="Model">
</div>

<partial name="_ModalDelete">
<partial name="_ModalDetails">
<partial name="_ModalMessage">


@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            $(document).on('show.bs.modal', '#delete-modal', function (e) {
                var id = $(e.relatedTarget).closest('tr').prop('id');
                $('#confirm-delete').data('id', id);

            });

            $(document).on('click', '#confirm-delete', function () {
                var id = $(this).data('id');
                $.ajax({
                    cache: false,
                    type: 'POST',
                    url: '@Url.Action("Delete","SEPhase")/' + id,
                    success: function (data) {
                        $('#delete-modal').modal('hide');
                        $('#list').html(data);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        $('#text-message-modal').html(xhr.responseText)
                        $('#delete-modal').modal('hide');
                        $('#message-modal').modal('show');
                    }
                });
            });

            $(document).on('click', '#details-button', function () {

                var id = $(this).closest('tr').prop('id');

                $.ajax({
                    cache: false,
                    type: 'GET',
                    url: '@Url.Action("Details","SEPhase")/' + id,
                    success: function (data) {
                        $('#modal-replace-body').html(data);
                        $('#modal-replace-body :input').prop('disabled', true);
                        $('#details-modal').modal('show');
                    }
                });

            })

        });
     </script>

}

MVC/Views/SEPhase/TableList.cshtml
@model SEPhaseIndexViewModel;
<div class="d-flex justify-content-center">

    <div class="table-responsive col-md-12">
        <table class="table table-striped table-bordered" cellspacing="0" cellpadding="0" style="font-size: smaller;">
            <thead>
                <tr>
                    @*<th class="w-75">Phase</th>

                        <th class="actions">Actions</th>*@
                    <th class="w-75">Fase da Engenharia de Software</th>

                    <th class="actions">Ações</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {

                    @foreach (var item in Model.SEPhaseList)
                    {
                        <tr id="@item.Id">
                            <td class="w-75">@item.Phase</td>
                            <td class="actions">
                                <a href="#" id="details-button" class="btn"><i class="fa fa-search"></i></a>
                                @if (Model.IsAdmin || Model.CurrentUserId == item.UserId)
                                {
                                    <a asp-controller="SEPhase" asp-action="Edit" asp-route-id="@item.Id" class="btn"><i class="fa fa-edit"></i></a>
                                    <a href="#" id="remove-button" class="btn" data-toggle="modal" data-target="#delete-modal"><i class="fa fa-trash"></i></a>
                                }
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

</div>

@*<nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Anterior</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Próxima</a>
            </li>
        </ul>
    </nav>*@