MVC/Controllers/EffectConsequenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Domain.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Services.Interfaces;
using Services.ViewModels;

namespace MVC.Controllers
{
    public class EffectConsequenceController : Controller
    {
        private readonly IEffectConsequenceService _effectConsequenceService;


        public EffectConsequenceController(IEffectConsequenceService effectConsequenceService)
        {
            _effectConsequenceService = effectConsequenceService;
        }

        public IActionResult Index()
        {
            //ViewBag.Title = "Effect Consequence";
            ViewBag.Title = "Efeitos e Consequências";

            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;


            var indexViewModel = new EffectConsequenceIndexViewModel()
            {
                EffectConsequenceList = _effectConsequenceService.GetAll().ToList(),
                CurrentUserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value),
                IsAdmin = isAdmin
            };
            return View(indexViewModel);

        }

        public IActionResult Create()
        {
            //ViewBag.Title = "Effect Consequence - Create";
            ViewBag.Title = "Efeitos e Consequências / Criar";
            return View(new EffectConsequenceViewModel());
        }

        public IActionResult CreateModal()
        {
            //ViewBag.Title = "Effect Consequence - Create";
            ViewBag.Title = "Efeitos e Consequências / Criar";
            return PartialView(nameof(Create), new EffectConsequenceViewModel() { FromModal = true });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EffectConsequenceViewModel effectConsequenceViewModel)
        {
            if (ModelState.IsValid)
            {
                effectConsequenceViewModel.UserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value);

                _effectConsequenceService.Add(effectConsequenceViewModel);

                if (effectConsequenceViewModel.FromModal)
                {
                    var scenarioConflictJourneyViewModel = new ScenarioConflictJourneyViewModel();
                    scenarioConflictJourneyViewModel.EffectConsequenceList = _effectConsequenceService.GetAll();
                    return PartialView("DropdownEffectConsequence", scenarioConflictJourneyViewModel);
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            if (effectConsequenceViewModel.FromModal)
            {
                Response.StatusCode = 400;
                return PartialView(nameof(Create), effectConsequenceViewModel);
            }
            else
            {
                return View(effectConsequenceViewModel);
            }
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var effectConsequenceViewModel = _effectConsequenceService.Get(id);
            if (effectConsequenceViewModel == null)
            {
                return NotFound();
            }
            return PartialView(effectConsequenceViewModel);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var viewModel = _effectConsequenceService.Get(id);
            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var canEdit = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value).Equals(viewModel.UserId.Value);

            if (!isAdmin && !canEdit)
            {
                return Unauthorized();
            }

            var effectConsequenceViewModel = _effectConsequenceService.Get(id);
            if (effectConsequenceViewModel == null)
            {
                return NotFound();
            }
            return View(effectConsequenceViewModel);
        }

        [HttpPost]
        public IActionResult Edit(int id, EffectConsequenceViewModel effectConsequenceViewModel)
        {
            ViewBag.Title = "Efeitos e Consequências / Editar";

            if (id != effectConsequenceViewModel.Id)
            {
                return NotFound();
            }

            var viewModel = _effectConsequenceService.Get(id);
            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var canEdit = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value).Equals(viewModel.UserId.Value);

            if (!isAdmin && !canEdit)
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _effectConsequenceService.Update(effectConsequenceViewModel);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_effectConsequenceService.GetAll().Any(e => e.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(effectConsequenceViewModel);
        }

        [HttpGet]
        public IActionResult TableList()
        {
            return PartialView(_effectConsequenceService.GetAll());
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var viewModel = _effectConsequenceService.Get(id);
            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var canEdit = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value).Equals(viewModel.UserId.Value);

            if (!isAdmin && !canEdit)
            {
                return Unauthorized();
            }

            if (_effectConsequenceService.CanRemove(id))
            {
                _effectConsequenceService.Remove(id);
            }
            else
            {
                //return StatusCode(500, "This item is being used by some Scenario and can not be removed");
                return StatusCode(500, "Este item está sendo usado por algum Cenário e não pode ser removido");

            }



            var indexViewModel = new EffectConsequenceIndexViewModel()
            {
                EffectConsequenceList = _effectConsequenceService.GetAll().ToList(),
                CurrentUserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value),
                IsAdmin = isAdmin
            };

            return PartialView(nameof(TableList), indexViewModel);
        }
    }
}

MVC/Views/EffectConsequence/Create.cshtml
@model Services.ViewModels.EffectConsequenceViewModel;

<form asp-controller="EffectConsequence" asp-action="Create" method="post" class="form-horizontal" role="form" autocomplete="off">
    <partial name="FormControl" model="Model">
        @*<button id="save" class="btn btn-primary">Save</button>
        <a asp-controller="EffectConsequence" asp-action="Index" id="cancel" class="btn btn-secondary">Cancel</a>*@
        <button id="save" class="btn btn-primary">Salvar</button>
        @if (!Model.FromModal)
        {
            <a asp-controller="EffectConsequence" asp-action="Index" id="cancel" class="btn btn-secondary">Cancelar</a>
        }
</form>

MVC/Views/EffectConsequence/Details.cshtml
@model Services.ViewModels.EffectConsequenceViewModel;

<partial name="FormControl" model="Model">

MVC/Views/EffectConsequence/DropdownEffectConsequence.cshtml
@model Services.ViewModels.ScenarioConflictJourneyViewModel;

<label class="control-label font-weight-bold">6ª - Efeitos e Consequências</label>
<i class="far fa-question-circle" data-toggle="tooltip" data-placement="top" title="Quais foram os efeitos e consequências causados pelo conflito?"></i>

@*<select asp-for="@Model.EffectConsequenceIds" asp-items="@Model.EffectConsequenceSelectList" class="form-control dropdown-select2" multiple searchable="Search...">*@
<select asp-for="@Model.EffectConsequenceIds" asp-items="@Model.EffectConsequenceSelectList" class="form-control dropdown-select2" multiple searchable="Procurar...">
</select>

<span asp-validation-for="@Model.EffectConsequenceIds" class="text-danger"></span>

MVC/Views/EffectConsequence/Edit.cshtml
@model Services.ViewModels.EffectConsequenceViewModel;

    <form asp-controller="EffectConsequence" asp-action="Edit" method="post" class="form-horizontal" role="form" autocomplete="off">
        <input asp-for="UserId" type="hidden" />

        <partial name="FormControl" model="Model">
            @*<button id="save" class="btn btn-primary">Save</button>
            <a asp-controller="EffectConsequence" asp-action="Index" id="cancel" class="btn btn-secondary">Cancel</a>*@
            <button id="save" class="btn btn-primary">Salvar</button>
            <a asp-controller="EffectConsequence" asp-action="Index" id="cancel" class="btn btn-secondary">Cancelar</a>
    </form>

MVC/Views/EffectConsequence/FormControl.cshtml
@model Services.ViewModels.EffectConsequenceViewModel;

<input asp-for="Id" type="hidden" />
<input asp-for="FromModal" type="hidden" />

<div class="form-row">
    <div class="form-group col-6">
        <label asp-for="@Model.EffectAndConsequence" class="control-label"></label>
        @*<input asp-for="@Model.EffectAndConsequence" class="form-control" placeholder="Effect Consequence" />*@
        <input asp-for="@Model.EffectAndConsequence" class="form-control" placeholder="Efeitos e Consequências" />
        <span asp-validation-for="@Model.EffectAndConsequence" class="text-danger"></span>
    </div>
</div>

MVC/Views/EffectConsequence/Index.cshtml
@model EffectConsequenceIndexViewModel;

    <div class="d-flex justify-content-between bd-highlight mb-3">
        <div class="col-md-5">
            <h4>
                Lista de Efeitos e Consequências
            </h4>
        </div>
        <div class="col-md-4">

        </div>
        <div class="p-1 col-md-3 bd-highlight">
            @*<a asp-controller="EffectConsequence" asp-action="Create" class="btn btn-primary pull-right h2">New Item</a>*@
            <a asp-controller="EffectConsequence" asp-action="Create" class="btn btn-primary pull-right h2">Novo Efeito e Consequência</a>
        </div>



        <div class="p-1 col-md-6 bd-highlight">

            <div class="input-group h2">
                @*<input name="data[search]" class="form-control" id="search" type="text" placeholder="Search Items">*@
                @*<input name="data[search]" class="form-control" id="search" type="text" placeholder="Procurar Efeito e Consequência">*@
                @*<button class="btn btn-primary" type="submit">
                    <span class="fa fa-search"></span>
                </button>*@
            </div>

        </div>

    </div>



<div id="list">
    <partial name="TableList" model="Model">
</div>

<partial name="_ModalDelete">
<partial name="_ModalDetails">
<partial name="_ModalMessage">


@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            $(document).on('show.bs.modal', '#delete-modal', function (e) {
                var id = $(e.relatedTarget).closest('tr').prop('id');
                $('#confirm-delete').data('id', id);

            });

            $(document).on('click', '#confirm-delete', function () {
                var id = $(this).data('id');
                $.ajax({
                    cache: false,
                    type: 'POST',
                    url: '@Url.Action("Delete","EffectConsequence")/' + id,
                    success: function (data) {
                        $('#delete-modal').modal('hide');
                        $('#list').html(data);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        $('#text-message-modal').html(xhr.responseText)
                        $('#delete-modal').modal('hide');
                        $('#message-modal').modal('show');
                    }
                });
            });

            $(document).on('click', '#details-button', function () {

                var id = $(this).closest('tr').prop('id');

                $.ajax({
                    cache: false,
                    type: 'GET',
                    url: '@Url.Action("Details","EffectConsequence")/' + id,
                    success: function (data) {
                        $('#modal-replace-body').html(data);
                        $('#modal-replace-body :input').prop('disabled', true);
                        $('#details-modal').modal('show');
                    }
                });

            })

        });
     </script>

}

MVC/Views/EffectConsequence/TableList.cshtml
@model EffectConsequenceIndexViewModel;
<div class="d-flex justify-content-center">

    <div class="table-responsive col-md-12">
        <table class="table table-striped table-bordered" cellspacing="0" cellpadding="0" style="font-size: smaller;">
            <thead>
                <tr>
                    @*<th class="w-75">Effect Consequence</th>

                        <th class="actions">Actions</th>*@
                    <th class="w-75">Efeitos e Consequências</th>

                    <th class="actions">Ações</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {

                    @foreach (var item in Model.EffectConsequenceList)
                    {
                        <tr id="@item.Id">
                            <td class="w-75">@item.EffectAndConsequence</td>
                            <td class="actions">
                                <a href="#" id="details-button" class="btn"><i class="fa fa-search"></i></a>
                                @if (Model.IsAdmin || Model.CurrentUserId == item.UserId)
                                {
                                    <a asp-controller="EffectConsequence" asp-action="Edit" asp-route-id="@item.Id" class="btn"><i class="fa fa-edit"></i></a>
                                    <a href="#" id="remove-button" class="btn" data-toggle="modal" data-target="#delete-modal"><i class="fa fa-trash"></i></a>
                                }
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

</div>

@*<nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Anterior</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Próxima</a>
            </li>
        </ul>
    </nav>*@