MVC/Controllers/InterviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using AutoMapper;
using Domain.Entities;
using Domain.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Services.Interfaces;
using Services.ViewModels;

namespace MVC.Controllers
{
    public class InterviewController : Controller
    {
        private readonly IInterviewService _interviewService;


        public InterviewController(IInterviewService interviewService)
        {
            _interviewService = interviewService;
        }

        public IActionResult Index()
        {
            //ViewBag.Title = "Interview";
            ViewBag.Title = "Entrevista";

            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;


            var indexViewModel = new InterviewIndexViewModel()
            {
                InterviewList = _interviewService.GetAll().ToList(),
                CurrentUserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value),
                IsAdmin = isAdmin
            };
            return View(indexViewModel);

        }

        public IActionResult Create()
        {
            //ViewBag.Title = "Interview - Create";
            ViewBag.Title = "Entrevista / Criar";
            return View(new InterviewViewModel() { Realization = DateTime.Now });
        }

        public IActionResult CreateModal()
        {
            //ViewBag.Title = "Interview - Create";
            ViewBag.Title = "Entrevista / Criar";
            return PartialView(nameof(Create), new InterviewViewModel() { FromModal = true, Realization = DateTime.Now });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(InterviewViewModel interviewViewModel)
        {

            if (ModelState.IsValid)
            {
                interviewViewModel.UserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value);

                _interviewService.Add(interviewViewModel);

                if (interviewViewModel.FromModal)
                {
                    var scenarioGeneralViewModel = new ScenarioGeneralViewModel();
                    scenarioGeneralViewModel.InterviewList = _interviewService.GetAll();
                    return PartialView("DropdownInterview", scenarioGeneralViewModel );
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            if (interviewViewModel.FromModal)
            {
                Response.StatusCode = 400;
                return PartialView(nameof(Create), interviewViewModel);
            }
            else
            {
                return View(interviewViewModel);
            }
        }

        public IActionResult Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var interviewViewModel = _interviewService.Get(id);
            if (interviewViewModel == null)
            {
                return NotFound();
            }
            return PartialView(interviewViewModel);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {

            ViewBag.Title = "Entrevista / Editar";

            if (id == 0)
            {
                return NotFound();
            }

            var viewModel = _interviewService.Get(id);
            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var canEdit = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value).Equals(viewModel.UserId.Value);

            if (!isAdmin && !canEdit)
            {
                return Unauthorized();
            }

            var interviewViewModel = _interviewService.Get(id);
            if (interviewViewModel == null)
            {
                return NotFound();
            }
            return View(interviewViewModel);
        }

        [HttpPost]
        public IActionResult Edit(int id, InterviewViewModel interviewViewModel)
        {
            if (id != interviewViewModel.Id)
            {
                return NotFound();
            }

            var viewModel = _interviewService.Get(id);
            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var canEdit = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value).Equals(viewModel.UserId.Value);

            if (!isAdmin && !canEdit)
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _interviewService.Update(interviewViewModel);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_interviewService.GetAll().Any(e => e.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(interviewViewModel);
        }

        [HttpGet]
        public IActionResult TableList()
        {
            return PartialView(_interviewService.GetAll());
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var viewModel = _interviewService.Get(id);
            var isAdmin = (Roles)Enum.Parse(typeof(Roles), HttpContext.User.FindFirst(ClaimTypes.Role).Value) == Roles.Admin;

            var canEdit = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value).Equals(viewModel.UserId.Value);

            if (!isAdmin && !canEdit)
            {
                return Unauthorized();
            }

            if (_interviewService.CanRemove(id))
            {
                _interviewService.Remove(id);
            }
            else
            {
                //return StatusCode(500, "This item is being used by some Scenario and can not be removed");
                return StatusCode(500, "Este item está sendo usado por algum Cenário e não pode ser removido");
            }


            var indexViewModel = new InterviewIndexViewModel()
            {
                InterviewList = _interviewService.GetAll().ToList(),
                CurrentUserId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.Hash).Value),
                IsAdmin = isAdmin
            };

            return PartialView(nameof(TableList), indexViewModel);
        }

    }
}

MVC/Views/Interview/Create.cshtml
@model Services.ViewModels.InterviewViewModel;

<form asp-controller="Interview" asp-action="Create" method="post" class="form-horizontal" role="form" autocomplete="off">
    <partial name="FormControl" model="Model">
        @*<button id="save" class="btn btn-primary">Save</button>
        <a asp-controller="Interview" asp-action="Index" id="cancel" class="btn btn-secondary">Cancel</a>*@
        <button id="save" class="btn btn-primary">Salvar</button>
        <a asp-controller="Interview" asp-action="Index" id="cancel" class="btn btn-secondary">Cancelar</a>
</form>

MVC/Views/Interview/Details.cshtml
@model Services.ViewModels.InterviewViewModel;

<partial name="FormControl" model="Model">

MVC/Views/Interview/DropdownInterview.cshtml
@model Services.ViewModels.ScenarioGeneralViewModel;

<label asp-for="@Model.InterviewId" class="control-label"></label><span style="color:red"> *</span>
@*<i class="far fa-question-circle" data-toggle="tooltip" data-placement="top" title="Choose the Interview for this Scenario, if there is an associated Interview"></i>*@
<i class="far fa-question-circle" data-toggle="tooltip" data-placement="top" title="Escolha a Entrevista para esse Cenário, caso tenha uma Entrevista associada"></i>

@*<select asp-for="@Model.InterviewId" asp-items="@Model.InterviewSelectList" class="form-control dropdown-select2" searchable="Search...">*@
<select asp-for="@Model.InterviewId" asp-items="@Model.InterviewSelectList" class="form-control dropdown-select2" searchable="Procurar...">
    @*<option value="0">Select One</option>*@
    <option value="0">Selecione</option>
</select>

<span asp-validation-for="@Model.InterviewId" class="text-danger"></span>

MVC/Views/Interview/Edit.cshtml
@model Services.ViewModels.InterviewViewModel;

    <form asp-controller="Interview" asp-action="Edit" method="post" class="form-horizontal" role="form" autocomplete="off">
        <input asp-for="UserId" type="hidden" />

        <partial name="FormControl" model="Model">
            @*<button id="save" class="btn btn-primary">Save</button>
            <a asp-controller="Interview" asp-action="Index" id="cancel" class="btn btn-secondary">Cancel</a>*@

            <button id="save" class="btn btn-primary">Salvar</button>
            <a asp-controller="Interview" asp-action="Index" id="cancel" class="btn btn-secondary">Cancelar</a>
    </form>

MVC/Views/Interview/FormControl.cshtml
@model Services.ViewModels.InterviewViewModel;

<input asp-for="Id" type="hidden" />
<input asp-for="FromModal" type="hidden" />
<input asp-for="Realization" type="hidden" />

<div class="form-row">
    <div class="form-group col-4">
        <label asp-for="@Model.Title" class="control-label"></label>
        @*<input asp-for="@Model.Title" class="form-control" placeholder="Title" />*@
        <input asp-for="@Model.Title" class="form-control" placeholder="Título" />
        <span asp-validation-for="@Model.Title" class="text-danger"></span>
    </div>
    <div class="form-group col-4">
        <label asp-for="@Model.Interviewer" class="control-label"></label>
        @*<input asp-for="@Model.Title" class="form-control" placeholder="Title" />*@
        <input asp-for="@Model.Interviewer" class="form-control" placeholder="Entrevistador" />
        <span asp-validation-for="@Model.Interviewer" class="text-danger"></span>
    </div>
    <div class="form-group col-4">
        <label asp-for="@Model.Realization" class="control-label"></label>
        @*<input asp-for="@Model.Title" class="form-control" placeholder="Title" />*@
        <input asp-for="@Model.Realization" type="date" class="form-control" />
        <span asp-validation-for="@Model.Realization" class="text-danger"></span>
    </div>
</div>

MVC/Views/Interview/Index.cshtml
@model InterviewIndexViewModel;

    <div class="d-flex justify-content-between bd-highlight mb-3">
        <div class="col-md-3">
            <h4>
                Lista de Entrevistas
            </h4>
        </div>
        <div class="col-md-7">

        </div>
        <div class="p-1 col-md-2 bd-highlight">
            @*<a asp-controller="Interview" asp-action="Create" class="btn btn-primary pull-right h2">New Item</a>*@
            <a asp-controller="Interview" asp-action="Create" class="btn btn-primary pull-right h2">Nova Entrevista</a>
        </div>


        <div class="p-1 col-md-6 bd-highlight">

            <div class="input-group h2">
                @*<input name="data[search]" class="form-control" id="search" type="text" placeholder="Search Items">*@
                @*<input name="data[search]" class="form-control" id="search" type="text" placeholder="Procurar Entrevista">*@
                @*<button class="btn btn-primary" type="submit">
                    <span class="fa fa-search"></span>
                </button>*@
            </div>

        </div>

    </div>



<div id="list">
    <partial name="TableList" model="Model">
</div>

<partial name="_ModalDelete">
<partial name="_ModalDetails">
<partial name="_ModalMessage">


@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            $(document).on('show.bs.modal', '#delete-modal', function (e) {
                var id = $(e.relatedTarget).closest('tr').prop('id');
                $('#confirm-delete').data('id', id);

            });

            $(document).on('click', '#confirm-delete', function () {
                var id = $(this).data('id');
                $.ajax({
                    cache: false,
                    type: 'POST',
                    url: '@Url.Action("Delete","Interview")/' + id,
                    success: function (data) {
                        $('#delete-modal').modal('hide');
                        $('#list').html(data);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        $('#text-message-modal').html(xhr.responseText)
                        $('#delete-modal').modal('hide');
                        $('#message-modal').modal('show');
                    }
                });
            });

            $(document).on('click', '#details-button', function () {

                var id = $(this).closest('tr').prop('id');

                $.ajax({
                    cache: false,
                    type: 'GET',
                    url: '@Url.Action("Details","Interview")/' + id,
                    success: function (data) {
                        $('#modal-replace-body').html(data);
                        $('#modal-replace-body :input').prop('disabled', true);
                        $('#details-modal').modal('show');
                    }
                });

            })

        });
    </script>

}

MVC/Views/Interview/TableList.cshtml
@model InterviewIndexViewModel;
<div class="d-flex justify-content-center">

    <div class="table-responsive col-md-12">
        <table class="table table-striped table-bordered" cellspacing="0" cellpadding="0" style="font-size: smaller;">
            <thead>
                <tr>
                    @*<th class="w-75">Title</th>

                        <th class="actions">Actions</th>*@
                    <th class="w-75">Título</th>

                    <th class="actions">Ações</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {

                    @foreach (var item in Model.InterviewList)
                    {
                        <tr id="@item.Id">
                            <td class="w-75">@item.Title</td>
                            <td class="actions">
                                <a href="#" id="details-button" class="btn"><i class="fa fa-search"></i></a>
                                @if (Model.IsAdmin || Model.CurrentUserId == item.UserId)
                                {
                                    <a asp-controller="Interview" asp-action="Edit" asp-route-id="@item.Id" class="btn"><i class="fa fa-edit"></i></a>
                                    <a href="#" id="remove-button" class="btn" data-toggle="modal" data-target="#delete-modal"><i class="fa fa-trash"></i></a>
                                }
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

</div>

@*<nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Anterior</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Próxima</a>
            </li>
        </ul>
    </nav>*@